name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          npm ci
          npm run format:check
          npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.eventname == 'push'
        run: npm run build
      - name: Deploy to Staging
        if: github.eventname == 'push'
        run: npx surge -project ./build --domain flagrant-clocks.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
